[package]
name = "reporta-billing"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
reporta-common.workspace = true
reporta-db.workspace = true
async-stripe = { version = "0.41.0", features = ["runtime-tokio-hyper-rustls"] }
tokio.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
tracing.workspace = true
thiserror.workspace = true
sqlx.workspace = true
uuid.workspace = true
